name: Android Release



on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: ubuntu-latest

   
    steps:
      
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      
      - uses: subosito/flutter-action@v2
        with:
        
          flutter-version: "3.0.0"
          # channel: 'stable'
    
      # - name: Get dependencies
      - run: flutter channel dev
      - run: flutter doctor
      - run: flutter pub get
      # - run: flutter test


      # Runs a set of commands using the runners shell
      - name: Start release build
      - run: flutter build apk 
      # - run: flutter build appbundle 
      - name: create github artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/release/*.apk
          token: ${{ secrets.TOKEN }

      - name: Upload app bundle artifact
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
        path: build/app/outputs/bundle/release/app-release.aab
      - name: Run Fastlane
        uses: maierj/fastlane-action@v1.4.0
        # uses: actions/upload-artifact@v1
        # with:
        #   name: release-apk
        #   