name: Android Release



on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: ubuntu-latest

   
    steps:
      
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      
      - uses: subosito/flutter-action@v2
        with:
        
          flutter-version: "3.0.0"
          # channel: 'stable'
    
      # - name: Get dependencies
      - run: flutter channel dev
      - run: flutter doctor
      - run: flutter pub get
      # - run: flutter test


      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build apk 
        # uses: actions/upload-artifact@v1
        # with:
        #   name: release-apk
        #   path: build/app/outputs/apk/release/app-release.apk